# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Oren Y. Kanner
tagline:          'Dreamer, Tinkerer, Hacker'
description:      'PhD Candidate in Mechanical Engineering at <a href="http://www.eng.yale.edu/grablab/" target="_blank">Yale University</a> studying robotics.  Also an aspiring hacker, writer, photographer, chef, etc.'
url:              http://orenyk.com

author:
  name:           'Oren Kanner'
  url:            http://orenyk.com

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/orenyk